### ISSUE TITLE
New Game, All Mods Loaded, All Configuration Done, Can't Move Character

### ISSUE THREAD

**Issue by neomewilson** [ForgottenGlory/Living-Skyrim#10]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

On a new game using 1.2.0 and following instructions; New Character, All Mods Loaded, All Mod Configurations completed according to guide. Character looks ahead, can't move them at all, can't go to statue to begin the game in earnest. 

I looked to make sure the Game-pad settings were turned off. I can open menus such as the Item menu but when I click on an item such as a book to read nothing happens.

**Comment by ForgottenGlory** [comment]
Disable Gamepad++ in MO2.

**Comment by neomewilson** [comment]
Perfect, I am not a Gamepad user so I was not aware of there being a mod to provide the functionality.  Everything is working great now that it is disabled. By the way, great build on the Living Skyrim. I have used all the different variations and really like yours and Phoenix the best.
