### ISSUE TITLE
ESL Possible Files

### ISSUE THREAD

**Issue by inire** [ForgottenGlory/Living-Skyrim#100]
**LS Version**
1.5.0

**Describe the bug**
a number of ESP's can be converted to ESL using xEdit

**To Reproduce**
run Wrye Bash, get a list of possible files, change the flag.

**Expected behavior**
More space for other mods.

**Screenshots**
N/A

**Additional context**
Here's the list I had when opening right after installing 1.5.0

FloraRespawnFix.esp
IA AllGUD Patch.esp
WICO - USSEP Compatible Patch.esp
Better Skill and Quest Books Names SE.esp
RaceMenu.esp
RaceMenuPlugin.esp
AOS Merged.esp
1nivWICSkyCloaksPatch.esp
Bandolier for NPCs Merged.esp
Improved Traps.esp
SparklesSE.esp
Apophysis_DPM_SE.esp
Obsidian_TS_Patch_Spectral.esp
CBBE.esp
RaceMenuMorphsCBBE.esp
OBIS SE - Immersive Weapons Patch.esp
PeopleAreStrangers.esp
Runandwalkpaces.esp
sandboxcylinderheight.esp
Dragon Stalking Fix.esp
Fixed body collision.esp
HornsAreForever.esp
NoBSAIProjectileDodge.esp
SkyHUD.esp
Celtic Music in Skyrim - Combat.esp
Celtic_Music_In_Skyrim_SE.esp
Celtic_Music_In_Skyrim_SE_Dungeon.esp
SPTConsistentOlderPeopleSE.esp
Men of Winter - Compatibility Patch.esp
WICO - Immersive Character.esp
Pre-Bash Merge.esp
kryptopyr's Merged.esp
YOT Merged.esp
EBQO Merged.esp
Dual Wield Parrying_SKSE.esp
RWT Lod Fix.esp
enemies_releveled.esp
LS Bashed Patch Override.esp
GAR Patches Merged.esp
zPatch.esp
widescreen_skyui_fix.esp

**Comment by inire** [comment]
doing a test run now using this ESL set.

**Comment by ForgottenGlory** [comment]
Thank you for putting this list together, I'll take a look and update as needed for 1.6.0 when it's ready.

**Comment by inire** [comment]
There's a few in there that don't work as ESL, I am narrowing it down, will update with the ones that work later this weekend.

**Comment by inire** [comment]
Successfully tested using these, will add more as I get done testing them.

FloraRespawnFix.esp
IA AllGUD Patch.esp
WICO - USSEP Compatible Patch.esp
Better Skill and Quest Books Names SE.esp
RaceMenu.esp
RaceMenuPlugin.esp
RaceMenuMorphsCBBE.esp
1nivWICSkyCloaksPatch.esp
Obsidian_TS_Patch_Spectral.esp
OBIS SE - Immersive Weapons Patch.esp
Men of Winter - Compatibility Patch.esp
widescreen_skyui_fix.esp

**Comment by ForgottenGlory** [comment]
I have a list of ESPs that can be ESL'd, will be included in 1.6.0

**Comment by ForgottenGlory** [comment]
Thank you for your work on this, I'll be using your list as well.
