### ISSUE TITLE
Level 30 enemies at early game.

### ISSUE THREAD

**Issue by aryell2linx** [ForgottenGlory/Living-Skyrim#102]
**LS Version**
1.5.2

**Describe the bug**
Level scaling of enemies is inconsistent. 

**To Reproduce**
Random encounters mainly, console info points to "Populated Skyrim Legendary.esp". "Sky-TEST", Immersive creatures SE.

**Expected behavior**
+/- few levels around player character level.
Exact info and IDs are in the screenshots.

**Screenshots**
![20200404223954_1](https://user-images.githubusercontent.com/63164998/78460148-2b955d80-76c7-11ea-90c8-e9cefa33a387.jpg)
![20200404224147_1](https://user-images.githubusercontent.com/63164998/78460149-2cc68a80-76c7-11ea-8dd5-a10f7e1d0d1f.jpg)
![20200404224207_1](https://user-images.githubusercontent.com/63164998/78460150-2cc68a80-76c7-11ea-8a65-0aee566389c6.jpg)
![20200404224225_1](https://user-images.githubusercontent.com/63164998/78460152-2d5f2100-76c7-11ea-9c49-d647233590ac.jpg)
![20200404224416_1](https://user-images.githubusercontent.com/63164998/78460153-2d5f2100-76c7-11ea-9f15-6cc050e55ca0.jpg)

**Additional context**
Multiple mods as seen in the screenshots uploaded seem to affect the scaling, including POP skyrim Legendary, the worst offender, with enemies at Level 30, other mods like sky-test, not so sure: aggresive Elks at level 15, and Immersive Creatures se, with human enemies at level 14

**Comment by ForgottenGlory** [comment]
The ones mentioned have been fixed, but this may be an issue that will need to be fixed as it comes up similar to darkface bugs. Fixed for now with 1.5.3

**Comment by aryell2linx** [comment]
Most enemies, that I see with this exact level (30) seem to be spawned randomly by Populated Skyrim Legendary.esp when on the roads, or inside caves sometimes where bandits usually are. I do not know your process, yet. But this issue is linked to this mod : Populated Skyrim HELL EDITION. I guess it ain't called Hell edition for no reason. When I say "bandits" I mean any potential enemy that this mod has in its lists. Short of eliminating the mod altogether from future releases of LS. I do not see a potential fix. Or modding the mod, overhauling it yourself or your team. (And I guess, there are permissions issues and time-constraints involved to do that).
By itself, I installed this in a my own modding adventures, trying to breath life into Skyrim (Only to find death instead 😄 ), and this bug came up even then. About 1-2 years ago.
