### ISSUE TITLE
GLENMORIL SE

### ISSUE THREAD

**Issue by Onionhorse** [ForgottenGlory/Living-Skyrim#103]
**Mod Name**
GLENMORIL SE

**Mod Link**
https://www.nexusmods.com/skyrimspecialedition/mods/32998

**Why?**
It's an Extended Witch Hunt Quest Mod, it expands a bit of lore of existing character mentioned in Vigilant SE from Vicn and a lot of bosses
and it comes with an English patch here
https://www.nexusmods.com/skyrimspecialedition/mods/33146/?
And a few addons here
https://www.nexusmods.com/skyrimspecialedition/mods/32926

**Additional context**
https://www.nexusmods.com/skyrimspecialedition/mods/33075
Adds the weapons types LV list into Skyrim but they can be a bit lore breaking outside of its quest mod

**Comment by ForgottenGlory** [comment]
No Alduin save attached, rejected.

**Comment by Onionhorse** [comment]
Give me a few hours
