### ISSUE TITLE
Aringoth Black Face

### ISSUE THREAD

**Issue by ixanza** [ForgottenGlory/Living-Skyrim#104]
**LS Version**
1.5.2

**Describe the bug**
Aringoth in the Goldenglow Estate has a blackface

**To Reproduce**
Visit Aringoth in the Goldenglow Estate

**Expected behavior**
Normal looking face

**Screenshots**
![ScreenShot47](https://user-images.githubusercontent.com/5535758/78469222-d3f00400-7751-11ea-9df9-fba6f090c365.png)

**Comment by ForgottenGlory** [comment]
Fixed for 1.5.3
