### ISSUE TITLE
Invisible water

### ISSUE THREAD

**Issue by iamye1** [ForgottenGlory/Living-Skyrim#105]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in C:\NetScriptFramework\Crash**

**LS Version**
1.5.x

**Describe the bug**
There is invisible water in the White River. It is West of the Abandoned Prison In between the water fall and the bridge to the left of it. Fish are swimming in invisible water.

**To Reproduce**
Get within visual distance of the river.

**Expected behavior**
There should be visible water at that location.

**Screenshots**

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed 1.5.3
