### ISSUE TITLE
Invisible Shields

### ISSUE THREAD

**Issue by SirSulius** [ForgottenGlory/Living-Skyrim#106]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in C:\NetScriptFramework\Crash**

**LS Version**
1.5.2

**Describe the bug**
Painted shields from Immersive Armors appear invisible when equipped by both the player and NPCs, but still appears in the world to pick up.

**To Reproduce**
Equip a painted shield.
A shield can be found at the Skyforge in Whiterun behind the shield painting rack.
Quick command to get there: coc WhiterunSkyforge

**Expected behavior**
The shields should show on both the player and NPCs.

**Screenshots**
Light Painted Shield Equipped and Blocking:
![light painted shield](https://user-images.githubusercontent.com/63211568/78511327-cf374a00-7769-11ea-841b-351a7420b09b.jpg)
Heavy Painted Shield Equipped and Blocking:
![heavy painted shield](https://user-images.githubusercontent.com/63211568/78511326-c9416900-7769-11ea-82ec-747a5ff8ff00.jpg)

The painted shields still show on the ground:
![shields on ground](https://user-images.githubusercontent.com/63211568/78511330-d199a400-7769-11ea-9aba-a836195c9c96.jpg)

Vanilla shields still work:
![iron shield](https://user-images.githubusercontent.com/63211568/78511328-cfcfe080-7769-11ea-8525-6f7971fc5d8d.jpg)

**Additional context**
So far it only seems to be the painted shields. According to the Immersive Armors FAQ, the likely cause for invisible armors is that the mod was installed incorrectly. I tried reinstalling Immersive Armors completely but it did not change anything. I also reinstalled LS completely but it did not fix it either.

**Comment by ForgottenGlory** [comment]
Fixed for 1.5.3
