### ISSUE TITLE
Sanguinaire

### ISSUE THREAD

**Issue by CritLoren** [ForgottenGlory/Living-Skyrim#107]
**Mod Name**
Sanguinaire (Revised Edition - Skyrim Vampire and Lycanthropy Experience)

**Mod Link**
https://www.nexusmods.com/skyrimspecialedition/mods/26312/

**Why?**
The addition of vampire clans would add more life to the game and more available roleplaying scenarios. It also overhauls the werewolves as well so there's more of a progression in that regard as well. Also, it's lore-friendly (since it literally adds all of this from previous lore)

**Comment by ixanza** [comment]
As per the announcement on FGs discord, please provide a save file where you’ve beaten Alduin in Living Skyrim to make suggestions

**Comment by CritLoren** [comment]
damn I thought that was a joke lmao, I'd rather not speedrun it for a single addition, but sure, I'll do that just for this suggestion.
