### ISSUE TITLE
Floating tree near Dumzbthar

### ISSUE THREAD

**Issue by Exoticusgaming** [ForgottenGlory/Living-Skyrim#109]
**LS Version**
Version 1.5.3

**Describe the bug**
There is a tree floating out of the ground near Dumzbthar in Solstheim.

**To Reproduce**
Walk near the entrance to Dumzbthar. See screenshots

**Expected behavior**
No floating tree.

**Screenshots**
![SkyrimSE 2020-04-09 00-02-12](https://user-images.githubusercontent.com/62580057/78862834-dc6c6700-79fd-11ea-890b-b748070a4ce1.png)
![SkyrimSE 2020-04-09 00-02-30](https://user-images.githubusercontent.com/62580057/78862845-dfffee00-79fd-11ea-8182-64e069ff9c29.png)

**Comment by aryell2linx** [comment]
Maybe check to see if in 1.5.4 it's fixed already, also this could require a manual fix or mod updates in LS modlist, also this is a very minor bug... I saw a floating box in Dawnstar Docks, but I could just fix it miself with the console and disable the box anyway, it's just there for the decor anyway...

**Comment by ForgottenGlory** [comment]
Can you possibly upload a screenshot of the tree selected in console? It will help me make sure I fix the right tree.

**Comment by aryell2linx** [comment]
Should i upload a screenshot with the dawnstar docks with console ... related to my comment earlier ?
Not really most urgent bug to repair, but I could do it quickly if you need it.

**Comment by ForgottenGlory** [comment]
Yes please! :)

**Comment by aryell2linx** [comment]
![20200410002220_1](https://user-images.githubusercontent.com/63164998/78942153-c58f4880-7ac1-11ea-868f-bcf8db0bf919.jpg)

**Comment by ForgottenGlory** [comment]
The tree has been fixed for 1.6.0.

The floating box and barrel I'm working on a fix for, they aren't static objects placed by a mod.
