### ISSUE TITLE
Forgotten Magic Redone SSE

### ISSUE THREAD

**Issue by natenater** [ForgottenGlory/Living-Skyrim#11]
**Mod Name**
Forgotten Magic Redone SSE

**Mod Link**
https://www.nexusmods.com/skyrimspecialedition/mods/12711

**Why?**
This is one of my favorite magic mods due to the high amount of customization the spells offer.

**Comment by Sparniaczek** [comment]
I also love this one.

**Comment by ForgottenGlory** [comment]
Note to self: Also needs https://www.nexusmods.com/skyrimspecialedition/mods/16669

**Comment by ForgottenGlory** [comment]
Added v1.4.0
