### ISSUE TITLE
missing water near Hillgrund's Tomb area

### ISSUE THREAD

**Issue by aryell2linx** [ForgottenGlory/Living-Skyrim#110]
**LS Version**
1.6.0

**Describe the bug**
Screenshots are self explanatory.

**To Reproduce**
Went from Riverwood to that area Hillgrund's Tomb exterior near the brigde.

**Expected behavior**
Water should exist, it actually treats the area like there is land there.
This looks like a regression of bug #105 Invisible Water.

**Screenshots**
![20200410100912_1](https://user-images.githubusercontent.com/63164998/78973001-a91dfb00-7b17-11ea-93c3-c47eb9654f1a.jpg)
![20200410100916_1](https://user-images.githubusercontent.com/63164998/78973004-aa4f2800-7b17-11ea-8922-55bc329a3873.jpg)
![20200410100951_1](https://user-images.githubusercontent.com/63164998/78973006-aa4f2800-7b17-11ea-91a2-16903164462f.jpg)
![20200410103335_1](https://user-images.githubusercontent.com/63164998/78973008-aae7be80-7b17-11ea-9e36-de96f685d77c.jpg)

**Additional context**
Did not do any mcm settings, just waited for the messages to disappear, then Riverwood inn alt start. And TGM... then I ran across the map to see if I have any CTD, witch I don't yet.
Should I do the MCM's first ?...

**Comment by aryell2linx** [comment]
Here is a waterfix.esp file fixing this issue as well as the water seem near the guardian stones.
>>> LunarDelta deserves all the credit <<<

proof:
(![20200410185812_1](https://user-images.githubusercontent.com/63164998/79005143-efe31380-7b5e-11ea-881a-eb89e977988d.jpg))
![20200410185606_1](https://user-images.githubusercontent.com/63164998/79005154-f40f3100-7b5e-11ea-9bee-042df7da0b9f.jpg)
![20200410185620_1](https://user-images.githubusercontent.com/63164998/79005156-f4a7c780-7b5e-11ea-9d80-8be417138e66.jpg)

LINK TO ESP:
https://cdn.discordapp.com/attachments/688593507966779453/698198229279441006/Waterfixes.esp

Just put this file in overwrite folder and activate as last in the mo2 plugin list. Or alternatively create an empty mod with this file inside in Mod Organizer 2.

**Comment by ForgottenGlory** [comment]
Fixed for 1.6.2
