### ISSUE TITLE
Weird camera when studying spell notes + some other weirdness.

### ISSUE THREAD

**Issue by aryell2linx** [ForgottenGlory/Living-Skyrim#111]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in C:\NetScriptFramework\Crash**

**LS Version**
1.6.0 also previous versions of 1.5.x and 1.4.3?

**Describe the bug**
Camera gets wonky when studying spell notes... sometimes. Recently restarted the game to activate steam overlay for screenshot purpose and it still happens... although the overlay(s) are turned off when playing normally.

**To Reproduce**
Study any spell note. Sometimes the camera is normal, but after a few more study session... well see screenshots... wish I could make a video, you can actually move the mouse and the camera centers somewhat on player character, but the angles are crazy.

**Expected behavior**
See the character in normal position in third person...

**Screenshots**
![20200411143908_1](https://user-images.githubusercontent.com/63164998/79042793-5f124380-7c03-11ea-8879-56efff8b702b.jpg)
![20200411143947_1](https://user-images.githubusercontent.com/63164998/79042796-60dc0700-7c03-11ea-8b9c-2ce61d0c58c7.jpg)
![20200411143958_1](https://user-images.githubusercontent.com/63164998/79042797-61749d80-7c03-11ea-91a2-6c360dd63ffb.jpg)

**Additional context**
Seems to happen with a minds of it's own. Might be hard to replicate on your end. But it happens to me on all the versions of Living Skyrim I've tried so far.

On a funny side note... did not have the chance to take screenshots (no overlay available at the time... iNeed is acting up strangely. Besides the delay in spoilage in inventory of Player character the a Cheese wheels in game (so far) turned not into cheese wedges but tomatoes (in list of foods) but still had the model of a cheese wedge in player inventory... with a massive delay I might add. The fix for this weird iNeed bug was just to restart the game and everything was back to "cheese" again.
(No CTDs so far)

**Comment by ForgottenGlory** [comment]
Not sure what could be causing the camera issue, is anyone else able to confirm this?
