### ISSUE TITLE
Immersive Needs

### ISSUE THREAD

**Issue by ForgottenGlory** [ForgottenGlory/Living-Skyrim#112]
**Mod Name**
Immersive Needs

**Mod Link**
https://www.nexusmods.com/skyrimspecialedition/mods/29317?tab=posts

**Why?**
Long story short: iNeed is too invasive and does things beyond its scope (such as modifying how Diseases work). This is a much simpler and more consistent alternative.

**Comment by aryell2linx** [comment]
i guess, cheese wheels won't become tomatoes no more :) because of iNeed... see bug #111
