### ISSUE TITLE
Floaty Flora Near Blind Cliff Cave

### ISSUE THREAD

**Issue by daffodilian** [ForgottenGlory/Living-Skyrim#113]
**LS Version**
1.6.1

**Describe the bug**
Just some floating plants, a tree, and some rocks just northeast of blind cliff cave, right after the fallen tree

**To Reproduce**
Go to blind cliff cave, walk north east down road, as soon as pass the fallen tree look to the north.

**Expected behavior**
Things will be floating, rocks look unfinished.
**Screenshots**
![ScreenShot57](https://user-images.githubusercontent.com/63564258/79081403-1930aa80-7ceb-11ea-9acc-d51806ac7d4c.png)
![ScreenShot55](https://user-images.githubusercontent.com/63564258/79081405-1afa6e00-7ceb-11ea-9ad0-2a3fbec3e5e9.png)
![ScreenShot56](https://user-images.githubusercontent.com/63564258/79081406-1d5cc800-7ceb-11ea-938b-1a8fa5caf26c.png)

**Comment by ForgottenGlory** [comment]
Fixed for 1.6.2
