### ISSUE TITLE
LOTD's Guard's Armor Replacer Patch isn't installed

### ISSUE THREAD

**Issue by ixanza** [ForgottenGlory/Living-Skyrim#114]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in C:\NetScriptFramework\Crash**

**LS Version**
1.5.2, confirmed its not installed on 1.6 as well

**Describe the bug**
The patch for Guards Armor Replacer isn't installed for LOTD Patches making it impossible to display guards armor in the museum

**Comment by aryell2linx** [comment]
Same here..., might have some weird connection with master of disguise as well... someone else in chat mentioned not working correctly with the guard armors replacers... he kept being attacked while wearing Whiterun Guard's armor (replacer variant)... So might be something there too...

**Comment by ForgottenGlory** [comment]
Fixed for 1.6.2
