### ISSUE TITLE
Immersive Jewelry

### ISSUE THREAD

**Issue by MagnusHellfire** [ForgottenGlory/Living-Skyrim#116]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in C:\NetScriptFramework\Crash**

**LS Version**
1.6.1

**Describe the bug**
Immersive jewelry adds a weight to septims, 1.5.4 had a patch for this but is not included in 1.6.1

**To Reproduce**
Steps to reproduce the behavior: Check xEdit 

**Additional context**
Changing the weight value in xEdit to 0.000000 will solve.

**Comment by ixanza** [comment]
Master of disguise was removed on his list causing 4 mods not to work as missing masters. this isn't a bug
