### ISSUE TITLE
Floating Tree Lake View Manor

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim#117]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in C:\NetScriptFramework\Crash**

**LS Version**
1.6.1

**Describe the bug**
Floating tree lakeview manor

**To Reproduce**
look at tree

**Expected behavior**
floating tree

**Screenshots**
![Capture](https://user-images.githubusercontent.com/62785432/79253673-354a5e00-7e49-11ea-9eeb-87a8f932c5e0.PNG)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed for 1.6.2
