### ISSUE TITLE
Transparent ritual table in Hjerim manor

### ISSUE THREAD

**Issue by Kuzym** [ForgottenGlory/Living-Skyrim#118]
**LS Version**
1.6.1 (latest)

**Describe the bug**
Ritual table is transparent and invisible from certain angles.

**Screenshots**
![ScreenShot60](https://user-images.githubusercontent.com/24378982/79277795-d289ae80-7eaa-11ea-9eb5-d134b258928c.png)

**Comment by ForgottenGlory** [comment]
Fixed for 1.6.2

**Comment by ForgottenGlory** [comment]
Well, I thought I could fix this, but I haven't been able to. If anyone knows a solution I'd be happy to implement it.
