### ISSUE TITLE
Numerous object mismatches in 3DNPC cave

### ISSUE THREAD

**Issue by Kuzym** [ForgottenGlory/Living-Skyrim#119]
![ScreenShot64](https://user-images.githubusercontent.com/24378982/79284252-61ea8e00-7eba-11ea-9863-adb1c2431761.png)

Location: Frost Peak Cave
Issue: Floating objects, objects stuck in shelves, clipping.

Not sure what causes this behaviour, to be honest. Latest version, no added mods.

**Comment by ForgottenGlory** [comment]
Fixed for 1.6.2
