### ISSUE TITLE
Arkngthamz tonal lock puzzle room very, very dark

### ISSUE THREAD

**Issue by bdsdev** [ForgottenGlory/Living-Skyrim#120]
Seems like it's an ELE/cell data issue, tweaking the ENB settings didn't do much for it.

![arkng1](https://user-images.githubusercontent.com/23546059/79297977-98adad80-7e94-11ea-83db-e84bcc472798.jpg)
![arkng2](https://user-images.githubusercontent.com/23546059/79297982-9a777100-7e94-11ea-8581-aa10a870417d.jpg)
![arkng3](https://user-images.githubusercontent.com/23546059/79297984-9c413480-7e94-11ea-8789-2539d1c1082e.jpg)

**Comment by ForgottenGlory** [comment]
I'm able to see this as well but everything for the lighting looks fine in xEdit... I think it's just really dark here.
