### ISSUE TITLE
Missing water/river glitch

### ISSUE THREAD

**Issue by Kuzym** [ForgottenGlory/Living-Skyrim#122]
![ScreenShot71](https://user-images.githubusercontent.com/24378982/79467790-78016700-7ffe-11ea-9fb6-d6e8859ff4db.png)

Water texture glitch? There's simply no water. Northwest of Lost Knife Hideout. Right next to the bridge.

![ScreenShot72](https://user-images.githubusercontent.com/24378982/79467899-96fff900-7ffe-11ea-954c-29aeb4cd3abd.png)

**Comment by ForgottenGlory** [comment]
Fixed 1.6.2
