### ISSUE TITLE
Shadows change when moving, crouching etc. Standing still shows "different kind" of shadows.

### ISSUE THREAD

**Issue by M0rr1s0n** [ForgottenGlory/Living-Skyrim#126]
**LS Version**
1.6.3

**Describe the bug**
While moving around the landscape, the shadows of trees, signpost etc. disappear. When standing still they all reappear and behave normally.

**To Reproduce**
Just moving around, crouching or jumping. Changing direction via mouse does not affect the shadows.

**Expected behavior**
All shadows being displayed at once or not flickering when moving.

**Screenshots**
the following ZIP contains a short (compressed) video of the issue.
[1-18.04.2020.zip](https://github.com/ForgottenGlory/Living-Skyrim/files/4497349/1-18.04.2020.zip)

**Comment by ForgottenGlory** [comment]
Try changing your Skyrim.ini in MO2's INI Editor such that fSunShadowUpdateTime=0 and fSunUpdateThreshold=0. These numbers can be adjusted anywhere from 0 to 2, you may have to try a few different combinations to get the issue to go away.
