### ISSUE TITLE
Dragon Priest Mask not using Apophysis textures in game

### ISSUE THREAD

**Issue by Exoticusgaming** [ForgottenGlory/Living-Skyrim#131]
**LS Version**
1.6.5
**Describe the bug**
I noticed that when I equip a dragon priest mask it shows vanilla textures instead of the Apophysis Dragon Priest ones. It shows in the inventory menu, but not when equipped.

**To Reproduce**
Equip a dragon priest mask.

**Expected behavior**
Uses Apophysis Dragon Priest masks.
.
**Screenshots**

**Additional context**
I found that installing the Improved closed helmets - Apophysis patch fixed it.

**Comment by ForgottenGlory** [comment]
Fixed 1.7.0
