### ISSUE TITLE
Flickering Shadows

### ISSUE THREAD

**Issue by onedeaddonkey** [ForgottenGlory/Living-Skyrim#133]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in C:\NetScriptFramework\Crash**

**LS Version**
1.6.6

**Describe the bug**
I have shadow flickering in all environments and in all world cells. As my camera moves the shadows flicker in and out of existence. I have followed all of the suggested settings.

**To Reproduce**

**Expected behavior**
No flickering shadows?

**Screenshots**

**Additional context**

**Comment by ForgottenGlory** [comment]
Please post a video so I can confirm what the issue is. There are two separate lighting-related things this could be.

**Comment by onedeaddonkey** [comment]
Thanks for the quick response:

https://drive.google.com/file/d/1m1Fi_3qVmOpy93bw9l1uF2V88Gysl8CE/view?usp=sharing


Short video.

Should mention I started with the performance version of the ENB and was still getting flicker.  It was as bad (with lower frames) when I went to regular version of ENB for testing.

**Comment by ForgottenGlory** [comment]
Did you tweak any settings in your INI files? Try replacing them with these: 

[Shadow Fix INI.zip](https://github.com/ForgottenGlory/Living-Skyrim/files/4517922/Shadow.Fix.INI.zip)

**Comment by onedeaddonkey** [comment]
I will try those. No I did not tweak anything that was not in your guide. All base settings.

**Comment by onedeaddonkey** [comment]
> Did you tweak any settings in your INI files? Try replacing them with these:
> 
> [Shadow Fix INI.zip](https://github.com/ForgottenGlory/Living-Skyrim/files/4517922/Shadow.Fix.INI.zip)

Did not work. Still getting the flicker as in the video

**Comment by ForgottenGlory** [comment]
Alright, we're still working on this. Hopefully will have a fix soon.

**Comment by onedeaddonkey** [comment]
I sort of fixed the issue  but have a new one:

https://drive.google.com/file/d/1dQy8oRsyCkQfL2kEoFtf6-PXe8Sc3CC_/view?usp=sharing

iShadowMaskQuarter=2 

In Prefs.ini

But if you look at the video I now have this weird shadow/reflection thing going on on the left side of the screen.  Apologies for the audio LOL, watching joe Rogan at the same time.

**Comment by ForgottenGlory** [comment]
Try the latest 1.6.7 update, that should resolve the shadows issue hopefully.
