### ISSUE TITLE
Barter window causes crash

### ISSUE THREAD

**Issue by carollsh** [ForgottenGlory/Living-Skyrim#134]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in C:\NetScriptFramework\Crash**
[Crash_2020_4_22_11-34-6.txt](https://github.com/ForgottenGlory/Living-Skyrim/files/4518353/Crash_2020_4_22_11-34-6.txt)
[save.zip](https://github.com/ForgottenGlory/Living-Skyrim/files/4518360/save.zip)

I included the save file.

**LS Version**
1.6.5
**Describe the bug**
Game crashes when opening barter window

**To Reproduce**
Speak to the girl at the stall, select Show me your wares

**Expected behavior**
Barter window opens

If I'm missing something like mandatory save-file cleansing or anything, please let me know.

**Comment by ForgottenGlory** [comment]
Fixed in 1.7.0
