### ISSUE TITLE
Weater Seams around Morthal.

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim#136]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in C:\NetScriptFramework\Crash**

**LS Version**
1.6.7

**Describe the bug**
Water seam

**To Reproduce**
N/A

**Expected behavior**
None "seamed" water

**Screenshots**
![ScreenShot58](https://user-images.githubusercontent.com/62785432/80232185-1c486680-861a-11ea-8f60-0ea98de37807.png)
![ScreenShot55](https://user-images.githubusercontent.com/62785432/80232198-210d1a80-861a-11ea-85c4-ef6135478fde.png)
![ScreenShot56](https://user-images.githubusercontent.com/62785432/80232210-24a0a180-861a-11ea-872b-a924f68e5559.png)

**Additional context**
It's the in/around the marshland of marthal.

**Comment by ForgottenGlory** [comment]
Fixed 1.7.0
