### ISSUE TITLE
People are Strangers

### ISSUE THREAD

**Issue by DiscipleDarkfriend** [ForgottenGlory/Living-Skyrim#147]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in C:\NetScriptFramework\Crash**

**LS Version**
Put the version of the list you are on here. 1.6x

**Describe the bug**
People are strangers script is not applying to npcs added by populated hell edition.

**To Reproduce**
Steps to reproduce the behavior: Approach any npc from the mod Populated hell and see they are called Traveler, Adventurer so on. 

**Expected behavior**
A clear and concise description of what you expected to happen. All Npcs - Jarls should be labeled as stranger when hovering over them. 

**Screenshots**

**Additional context**

**Comment by ForgottenGlory** [comment]
Unable to fix, sorry
