### ISSUE TITLE
Weird water glitch.

### ISSUE THREAD

**Issue by schmingus** [ForgottenGlory/Living-Skyrim#150]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in C:\NetScriptFramework\Crash**

**LS Version**
1.6.9 (most recent)

**Describe the bug**
The water seems to be two different textures? It's hard to describe so i've provided screencaps, including DynDOLOD's You Are Here! MCM menu.

**To Reproduce**
I merely went to the location and it appeared. I've altered absolutely nothing to do with water and haven't done so much as change the LO.

**Expected behavior**
I expected the water to flow naturally, rather than two different textures.

**Screenshots**
![ScreenShot84](https://user-images.githubusercontent.com/64585767/80698072-df74e780-8ad1-11ea-80e4-4ea2b9f4ed9b.png)
![ScreenShot83](https://user-images.githubusercontent.com/64585767/80698421-5c07c600-8ad2-11ea-8934-3da83c79bf2a.png)
![ScreenShot80](https://user-images.githubusercontent.com/64585767/80698509-8063a280-8ad2-11ea-9b02-d67fb7a25713.png)

**Additional context**
I've never seen it before.

**Comment by ForgottenGlory** [comment]
Fixed 1.7.0
