### ISSUE TITLE
The Great Cities of JK's North - Patch

### ISSUE THREAD

**Issue by lucasraggi** [ForgottenGlory/Living-Skyrim#151]
**Mod Name**
The Great Cities of JK's North - Patch

**Mod Link**
https://www.nexusmods.com/skyrimspecialedition/mods/33687?tab=files

**Why?**
this patch make jk skyrim, great cities, and cities of the north (optional) compatible with each other, focusing on the positives of each mod

**Comment by ForgottenGlory** [comment]
This doesn't do anything without the great cities mods. Also no Alduin save.
