### ISSUE TITLE
[1.7.1] Reading Anything Instantly Improves Speech

### ISSUE THREAD

**Issue by HollerHavoc** [ForgottenGlory/Living-Skyrim#154]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in C:\NetScriptFramework\Crash**

**LS Version**
1.7.1

**Describe the bug**
I assume this bug is part of The Eloquent Reader but essentially what happens is; no matter the book read, be it a missive, small note, or great novel, your speech is instantly increased to the next level. As far as I can tell this didn't happen on 1.7.0.

**To Reproduce**

- Read any note or book

**Expected behavior**
Asking around apparently your speech is supposed to increase every 5-10 books read.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by pgdeaner** [comment]
Can't reproduce this issue.  Holler, do you have a save game you can post where this is still happening?

**Comment by HollerHavoc** [comment]
[Buggy Books.zip](https://github.com/ForgottenGlory/Living-Skyrim/files/4611387/Buggy.Books.zip)

**Comment by atomicpulsz** [comment]
Have the same error, can confirm.
