### ISSUE TITLE
College of Winterhold Multiple Repeated CTD's Upon Loading In

### ISSUE THREAD

**Issue by atomicpulsz** [ForgottenGlory/Living-Skyrim#155]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in C:\NetScriptFramework\Crash**

[Crash_2020_5_12_19-30-1.txt](https://github.com/ForgottenGlory/Living-Skyrim/files/4619005/Crash_2020_5_12_19-30-1.txt)

**LS Version**
Put the version of the list you are on here.
1.7.1
**Describe the bug**

Multiple CTD's in the COW cell area. CTD's upon entering Halls, attempted on Hall of Attainment and Hall of Acumen 5/6 times with CTD each time. Loading into game, the Configuring NFF message is displayed on top left despite it already having done so when first creating character.

To note, new character, first install. 

**To Reproduce**

Character creation -> mod config settings -> sleep in bed (multiple crashes loading into COW start) -> eventually loaded once saved, begun college tour quest. Followed Mirabelle into Hall of Attainment where it crashed upon loading.

**Expected behavior**

The interior loads normally. 

**Screenshots**

**Additional context**
Notable: vsync is disabled frame rate is capped at 144 via enb.

**Comment by pgdeaner** [comment]
Can't reproduce on a vanilla install.  Do you have a save that can reproduce this error?

**Comment by pgdeaner** [comment]
Can't reproduce on a clean install even with your ini settings.

**Comment by atomicpulsz** [comment]
[buggygame.zip](https://github.com/ForgottenGlory/Living-Skyrim/files/4619580/buggygame.zip)

Yup. I started a new game and reset my Skyrim.ini without changing [HAVOK] and it still crashed, seems like it wasn't the issue. Try the COW start with this. 

I was reseting my install so the saves got trashed but here's a new one from where I crash even trying to enter COW via Alternate Start.

**Comment by atomicpulsz** [comment]
Man, it seems to be CTD's all over when entering and leaving exteriors....since selecting college of winterhold didn't work I selected escape the prison cell, and the result was another crash when I tried to exit the door to skyrim. I saved right outside the door so it's easy to reproduce. @pgdeaner @ForgottenGlory 
[Crash_2020_5_12_23-7-10.txt](https://github.com/ForgottenGlory/Living-Skyrim/files/4619612/Crash_2020_5_12_23-7-10.txt)
[EscapingCell.zip](https://github.com/ForgottenGlory/Living-Skyrim/files/4619585/EscapingCell.zip)

**Comment by pgdeaner** [comment]
Well, I can't reproduce your issue with your save.  Only difference is that I am not running the widescreen fix.  I'd try a clean install of skyrim, then reinstall LS.
