### ISSUE TITLE
Sustained/Invested Magic feels redundant given the rest of the modlist

### ISSUE THREAD

**Issue by TalosMora** [ForgottenGlory/Living-Skyrim#157]
Suggestion for removal rather than addition. Given that half the perks in Conjuration, not to mention the Fortify Conjuration/Alteration enchantments, Necromancer's Amulet, etc. etc. all add duration to your spells, plus Occato's Recital and other's allow you to auto-cast things when entering combat, the choice of Sustained Magic doesn't make much sense. It removes the need to use any of the features mentioned here, and while the mod itself is balanced, it does not seem to accept Ordinator perks to reduce investment cost. Overall, it clutters what would otherwise be the most well-balanced magic gameplay I've ever experienced in Skyrim.

**Comment by ForgottenGlory** [comment]
Not happening.
