### ISSUE TITLE
Vortikai's Dragon Aspect Toggle

### ISSUE THREAD

**Issue by ForgottenGlory** [ForgottenGlory/Living-Skyrim#25]
Vortikai's Dragon Aspect Toggle | https://www.nexusmods.com/skyrimspecialedition/mods/8897/

Suggested by micmou

**Comment by micmou** [comment]
Great mod makes Dragon Aspect usable and a worthy reward.

**Comment by micmou** [comment]
I recomend the shout+magic buff version of the three

**Comment by micmou** [comment]
*scratches arm* Hey man you got any of them mod additions.

**Comment by ForgottenGlory** [comment]
This mod is low priority, I'll take a look at it when I get a chance.

**Comment by micmou** [comment]
Danke Shurn. Low impact addition does one specific thing that for people who like to use it changes there world.

**Comment by ForgottenGlory** [comment]
Added v1.5.0
