### ISSUE TITLE
Vigilant - NPC Overhaul

### ISSUE THREAD

**Issue by harold777** [ForgottenGlory/Living-Skyrim#31]
Vigilant - NPC Overhaul

Why: It makes npc's look a whole lot more memorable for such an awesome mod and it works pretty well it's very similar to Cuyima Interesting NPCs  but for vigilant

https://www.nexusmods.com/skyrimspecialedition/mods/22146/

**Comment by ForgottenGlory** [comment]
Added v1.5.0
