### ISSUE TITLE
Crash on loading character

### ISSUE THREAD

**Issue by Enigmacell0522** [ForgottenGlory/Living-Skyrim#32]
First crash occurred mid play in a conversation with Lucian at the beginning of the game. After that the game starts up fine but crashes near the end of loading up a save again.

Happens consistently every time. Character should currently be in Riverwood.

Not sure why it is crashing but full disclosure (and I did read your warning) I did install some extra mods. Most of them armor, The most complex mod I think i added was true spears. But like I said I had the game up and running fine and then like 10 minutes in it crashes and now I cannot load back up.

I have attached my logs if it helps. Still needing some help on troubleshooting my own problems.

[Papyrus.0.log](https://github.com/ForgottenGlory/Living-Skyrim/files/4362569/Papyrus.0.log)
[Papyrus.1.log](https://github.com/ForgottenGlory/Living-Skyrim/files/4362570/Papyrus.1.log)

Let me know if you need anything else.

Thank You

Edit: Also I think I may have messed with some game settings by opening up the game launcher.
may need ini settings.

**Comment by ForgottenGlory** [comment]
I cannot provide support when mods have been added.
