### ISSUE TITLE
Camping in the woods CTD bug.

### ISSUE THREAD

**Issue by pgdeaner** [ForgottenGlory/Living-Skyrim#34]
**Describe the bug**
Consistently crashes to the desktop.

**To Reproduce**
Start a new game.  Wait for scripts to complete.  Perform MCM configs per the guide.  Save.  Talk to mara and choose "I am camping in the woods".  Do not touch KB or mouse or move at all.  Will sometimes CTD.  If it does not immediately CTD, you may be able to choose a religion.  Then it will CTD when it tries to apply experience in the scripts that run.  

**Expected behavior**
No CTD

**Screenshots**

**Additional context**
It does not happen from the same save if other life options are selected.

**Comment by ForgottenGlory** [comment]
I'm unable to replicate this, further testing required. Anyone who wants to try is welcome to and can comment here with results.

**Comment by Denial7** [comment]
I had a CTD first time I selected Camping in the Woods, loaded up and tried again and it worked this time. It froze up for a second and had the spinning cursor after I selected my Wintersun deity, but was able to recover.

extra details: 6GB VRAM, 16GB RAM

**Comment by pgdeaner** [comment]
Did some more testing and it seems to hinge on the selection of diety.  When that's done it tries to autosave.  Chose whiterun and it was not a problem.

**Comment by ForgottenGlory** [comment]
Is it just one particular deity, or all of them?

**Comment by pgdeaner** [comment]
Fresh install SSE.  Fresh install of 1.3.2.  Latest NVIDIA driver.  Got to the religion question first time.  Now it CTD even before that menu displays.

**Comment by pgdeaner** [comment]
Hardware profile 9900K, 2080ti, 32GB RAM.

**Comment by ForgottenGlory** [comment]
Copied here for posterity: I'm 99% sure the CTDs people have been getting are due to an issue with DynDOLOD. DynDOLOD usually loads pretty close to Wintersun in-game, and there's another issue with some missing LODs. I was able to get the CTD before the Wintersun menu appeared, so I don't think it's that. 

I'll be checking it out tomorrow.

**Comment by pgdeaner** [comment]
Just for giggles, I went back to 1.1 and it happens there as well.  At least for me.  Seems like a lot is going on with that start.  I tried several others and they all work fine.

**Comment by pgdeaner** [comment]
If there is anything I can do to get you more data or to help please let me know.

**Comment by ForgottenGlory** [comment]
At this point pretty much anything would help:

Race(s) selected?
Deity(s) selected?
Any additions or changes to the list?
Gamepad++ or Widescreen fix enabled?
Windows version?
Any overlays enabled? (Discord, Steam, nVidia, etc.)
Anything else out of the ordinary? (something loading multiple times in the list in the top left, any weirdness with MCMs, etc.)

**Comment by pgdeaner** [comment]
Nord
Kynnereth when I have got that far.
No changes, fresh install. - disabled both Gamepad++ and widescreen fix.
No overlays.
All else is normal, but I will keep an eye out for the top of the list.
What I can tell you is that it crashes before Dyndolod loads.

**Comment by pgdeaner** [comment]
Well following this train of thought I unticked Dyndolod and tried it again.  Lo and behold.  It worked like magic.  :)

**Comment by Denial7** [comment]
Answers from me for the record, though it seems linked to Dyndolod:
Breton
Stendarr
No changes
Gamepad++ enabled, widescreen fix disabled
No overlays
No weirdness noticed

**Comment by pgdeaner** [comment]
This no longer occurs in the latest update.  Thank you!

**Comment by pgdeaner** [comment]
Denial7 mentioned that he was still seeing this.  I added several personal edited mods that I have checked for conflicts in xEdit.  Previously this seemed to make matters worse with the issue but I am still not able to reproduce.  As you noted, there is a pronounced pause in the game when you first start camping in the woods.  May be worth noting in the readme or something.  If you leave the game alone for a minute or so it finishes with scripts and you can proceed normally.
