### ISSUE TITLE
Dyndolod is missing data for cell zero / Whiterun

### ISSUE THREAD

**Issue by pgdeaner** [ForgottenGlory/Living-Skyrim#36]
**Describe the bug**
FG, when I enter whiterun I get an error that Dyndolod is missing data for cell zero.  

**To Reproduce**
Enter whiterun, stand around warmaiden's

**Expected behavior**
No error

**Screenshots**

**Additional context**
Just a heads up.

**Comment by ForgottenGlory** [comment]
Confirmed, working on a fix.

**Comment by pgdeaner** [comment]
No longer occurs in 1.3.3
