### ISSUE TITLE
Rock outside Whiterun 1.3.3 LS

### ISSUE THREAD

**Issue by tHiNgXX9** [ForgottenGlory/Living-Skyrim#38]
**Describe the bug**
A rock outside of Whiterun is missing a side of it and is able to be looked through.

**To Reproduce**
Walk to the side of the rock that is transparent
 
**Expected behavior**
The Rock not to be seen through.
![20200322132813_1](https://user-images.githubusercontent.com/62521502/77260113-31a92a00-6c43-11ea-8828-2c951ac6405e.jpg)

**Screenshots**
![20200322132813_1](https://user-images.githubusercontent.com/62521502/77260113-31a92a00-6c43-11ea-8828-2c951ac6405e.jpg)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed for 1.3.4.
