### ISSUE TITLE
Wards functionalities extended

### ISSUE THREAD

**Issue by BenGraham** [ForgottenGlory/Living-Skyrim#4]
**LE/Oldrim mods will be automatically rejected, do not submit them.**

**Mod Name**
Wards functionalities extended

**Mod Link**
https://www.nexusmods.com/skyrimspecialedition/mods/18664

**Why?**
Makes wards viable. Allows you to block melee and arrows using wards, change the magnitude and strength, duration, etc.

**Additional context**
Wards are essentially useless without this mod. Also has a compatibility patch for sustained magic.

**Comment by ForgottenGlory** [comment]
Added for v1.3.0
