### ISSUE TITLE
Maids II Deception

### ISSUE THREAD

**Issue by Sparniaczek** [ForgottenGlory/Living-Skyrim#40]
**Mod Name**
Maids II Deception

**Mod Link**
https://www.nexusmods.com/skyrimspecialedition/mods/189

**Why?**
It's a nice storyline mod with great voice acting and amazing locations.

**Comment by harold777** [comment]
this mod is kinda fulled to the max with heavy scripts might end up bloating and breaking saves in the long run with such a big list
