### ISSUE TITLE
Bleak falls barrow - Revisited

### ISSUE THREAD

**Issue by LookImEcho-Rick** [ForgottenGlory/Living-Skyrim#42]
**LE/Oldrim mods will be automatically rejected, do not submit them.**

**Mod Name**
Bleak falls barrow - Revisited

**Mod Link**
https://www.nexusmods.com/skyrimspecialedition/mods/33251

**Why?**
LS is about making the game feel more immersive and alive and this mod makes BFB actually feel like a MQ dungeon rather than random nordic dungeon #67;

**Additional context**
I would also recommend taking a look at Ustengrav - Revisited which is the same idea just diffident location.

https://www.nexusmods.com/skyrimspecialedition/mods/33251

**Comment by ForgottenGlory** [comment]
Duplicate of #18
