### ISSUE TITLE
Blackthorn

### ISSUE THREAD

**Issue by Sparniaczek** [ForgottenGlory/Living-Skyrim#44]
**Mod Name**
Blackthorn

**Mod Link**
https://www.nexusmods.com/skyrimspecialedition/mods/2242

**Why?**
Nice upgradable house in Riften

**Comment by ForgottenGlory** [comment]
Please check the [LS Modlist](https://docs.google.com/spreadsheets/d/1sKG690CbutxCFhDLfTH7C6yYCz0dOkZkuKfYAqRBRVU/edit?usp=sharing) before suggesting mods. Blackthorn is already included.
