### ISSUE TITLE
CTD trying to sell raw spider meat to Anoriath

### ISSUE THREAD

**Issue by pgdeaner** [ForgottenGlory/Living-Skyrim#48]
**Make sure you are using the latest version of LS before reporting a bug.**

**Describe the bug**
CTD

**To Reproduce**
Talk to Anoriath, Selected what do you have for sale?
Selected raw spider meat from my inventory.

**Expected behavior**
Sell the spider meat for something.

**Screenshots**

**Additional context**

**Comment by ForgottenGlory** [comment]
Should be fixed in 1.5.0
