### ISSUE TITLE
SSE Engine Fixes 4.13/MO2 issue fixable by version upgrade

### ISSUE THREAD

**Issue by bdsdev** [ForgottenGlory/Living-Skyrim#49]
**Describe the bug**
engine fixes 4.13 tries to load savefiles from the wrong path if you use MO profile saves.  version 5.1.0.1 of Engine fixes corrects this so the automatic co-save cleaner functionality will work again.

**Comment by ForgottenGlory** [comment]
What exactly is the "automatic co-save cleaner functionality" and why is it needed? Just looking for more information, thanks!

**Comment by ForgottenGlory** [comment]
Regardless, Engine Fixes updated for 1.3.4.
