### ISSUE TITLE
Duel Wield Blocking

### ISSUE THREAD

**Issue by BenGraham** [ForgottenGlory/Living-Skyrim#5]
**LE/Oldrim mods will be automatically rejected, do not submit them.**

**Mod Name**
(SJG) Dual Wield Parrying Reimplementation for SSE (Works for Spell Blades as well)

**Mod Link**
https://www.nexusmods.com/skyrimspecialedition/mods/18264

**Why?**
You can block with while dual wielding or using a spell in one hand and a sword in another.

**Additional context**
Seems pretty weird I can't parry with a one handed sword! This will increase immersion.

**Comment by pgdeaner** [comment]
There is also  - https://www.nexusmods.com/skyrimspecialedition/mods/16334
Key Bindable Dual Wield Blocking and Parrying - Attack canceling FTW.

**Comment by ForgottenGlory** [comment]
EverWatch's version included for 1.5.0 because some of the notes on Aralu's version worry me.
