### ISSUE TITLE
Quicksaves are no longer turned into manual saves.

### ISSUE THREAD

**Issue by SirTurlock** [ForgottenGlory/Living-Skyrim#52]
**Describe the bug**
Pressing F5 to create a manual save in 1.3.4 (latest) instead creates a quicksave.

**To Reproduce**
Press F5 in a loaded save.

**Expected behavior**
A manual save is created.

**Additional context**

The likely reason for this behavior is that RegularQuicksaves is set to false inside EngineFixes.ini instead of true.

**Comment by ForgottenGlory** [comment]
Fixed for 1.3.5, thanks!
