### ISSUE TITLE
optional ultrawidescreen support

### ISSUE THREAD

**Issue by bdsdev** [ForgottenGlory/Living-Skyrim#6]
**LE/Oldrim mods will be automatically rejected, do not submit them.**

**Mod Name**
Complete Widescreen Fix for SkyUI

**Mod Link**
https://www.nexusmods.com/skyrimspecialedition/mods/1778

**Why?**
I was pretty pleased to see optional gamepad++ support in this modlist, because it's one I generally have to include myself.  The other one I usually have to add are a set of UI fixes for 21:9 support, so I figure I'd suggest it for others in my situation too.

**Additional context**
Understandable if the suggestion is rejected because it's not really a 'core' sort of thing, and idk how feasible including a default-off option is.  But something to tick on to make a controlled as opposed to ad-hoc set of changes to the core UI setup would be pretty great.  (also understandable if the suggestion is rejected due to not having a 21:9 monitor for testing, heh)

**Comment by ForgottenGlory** [comment]
Added for 1.3.0, it will be initially disabled so it will still need to be turned on manually in MO2.
