### ISSUE TITLE
Ustengrav Revisited

### ISSUE THREAD

**Issue by ixanza** [ForgottenGlory/Living-Skyrim#61]
**LE/Oldrim mods will be automatically rejected, do not submit them.**

**Mod Name**
Ustengrav - Revisited

**Mod Link**
https://www.nexusmods.com/skyrimspecialedition/mods/33878

**Why?**
Pretty neat overhaul to one of the dungeons thats forced on you for main story

**Additional context**

**Comment by ForgottenGlory** [comment]
Added v1.6.0
