### ISSUE TITLE
Dolmens, Oblivion Gates, Laundry

### ISSUE THREAD

**Issue by Suraru** [ForgottenGlory/Living-Skyrim#62]
**Mod Links**
Holidays 			https://www.nexusmods.com/skyrimspecialedition/mods/1533
Laundry 			https://www.nexusmods.com/skyrimspecialedition/mods/20346
Dolmens 			https://www.nexusmods.com/skyrimspecialedition/mods/327
Oblivion Gates 	https://www.nexusmods.com/skyrimspecialedition/mods/9040
Skyshards 		https://www.nexusmods.com/skyrimspecialedition/mods/6331

**Why?**
Adds in missing lore details, from landmarks from other games, to simple life tasks. Recommend all as a group.

**Comment by ForgottenGlory** [comment]
Holidays is a broken mess, rejected.
Skyshards would mess with the balance of the list, rejected.

Dolmens, Oblivion Gates: I guess? Depends on what they look like conflict-wise.

Laundry: It does have a compatibility patch with JKs, so maybe.

**Comment by ForgottenGlory** [comment]
After thinking about this more, these are just clutter that don't really add anything to the game.
