### ISSUE TITLE
Hunters Not Bandits

### ISSUE THREAD

**Issue by Suraru** [ForgottenGlory/Living-Skyrim#67]
Stones of Barenziah		https://www.nexusmods.com/skyrimspecialedition/mods/686
Coin Purse			https://www.nexusmods.com/skyrimspecialedition/mods/6508
We don't float 			https://www.nexusmods.com/skyrimspecialedition/mods/16088
Torches ignite oil 		https://www.nexusmods.com/skyrimspecialedition/mods/13226
Hunters not bandits 	https://www.nexusmods.com/skyrimspecialedition/mods/1547

**Why?**
Minor QOL or fixes that can be merged

**Comment by ForgottenGlory** [comment]
Coin Purse - Loot is fine in the list currently.
We don't float: believe it or not, corpses *do* float.
Torches ignite oil: There are probably another dozen ways to set oil on fire, redundant.
Stones of Barenziah: it's supposed to be a challenge to find them all.

Hunters not bandits is the only one I'll consider from here.

**Comment by ForgottenGlory** [comment]
Hunters not bandits will be included in 1.6.0 when it's ready.
