### ISSUE TITLE
Frozen Electrocuted Combustion

### ISSUE THREAD

**Issue by Suraru** [ForgottenGlory/Living-Skyrim#68]
**LE/Oldrim mods will be automatically rejected, do not submit them.**

**Mod Name**
Frozen Electrocuted Combustion

**Mod Link**
https://www.nexusmods.com/skyrimspecialedition/mods/3532

**Why?**
Because I like seeing people I killed with fire burn to a crisp

**Comment by tr4wzified** [comment]
Would recommend against. Although a lovely mod for visuals, I'm pretty sure I've had crashes due to this one.
