### ISSUE TITLE
More Interesting Loot Reborn

### ISSUE THREAD

**Issue by icemaner1** [ForgottenGlory/Living-Skyrim#7]
More Interesting Loot Reborn

https://www.nexusmods.com/skyrimspecialedition/mods/24458

This mod add a lot of armor and weapon and other really interesting loot to the chest all around skyrim with them evolving the more are being used. 
I really miss this mod while playing your modlist. 

Also take a look at guards armor replacer and heavy legion i miss those also.
https://www.nexusmods.com/skyrimspecialedition/mods/22671
https://www.nexusmods.com/skyrimspecialedition/mods/22877

Living skyrim is the best modlist i've tried so far it's perfect also without those mods i suggested so dont add them if you dont feel like, thanks for your masterpiece.

PS sorry for my english it's a bit mixed with italian, my bad.

**Comment by ForgottenGlory** [comment]
Too many loot-modifying mods already.
