### ISSUE TITLE
Version 1.4.0 does not map drive location correctly for SKSE64 or Explorer++

### ISSUE THREAD

**Issue by inire** [ForgottenGlory/Living-Skyrim#71]
**Make sure you are using the latest version of LS before reporting a bug.**

**Describe the bug**
The following applications do not correct to the right paths after installing 1.4.0
SKSE (stays at C:\Steam...)
Explorer++ (stays at H:\)

**To Reproduce**
1. Install LS 1.4.0 through wabbajack (version 1.1.3.0) download page.
2. Move files into the correct directories from the Game Files Folder.
3. Open ModOrganizer2.
4. Check the executable paths to make sure they're pointed correctly.

**Expected behavior**
Files should have updated to the correct location (all the other executables do this).

**Screenshots**
N/A. Didn't think to get these darn it....

**Additional context**
I have a strange C directory structure for coding purposes, so most things are in c:\Local

**Comment by inire** [comment]
![Path Error 1 4 0](https://user-images.githubusercontent.com/12611289/77764857-b9ac7c80-7013-11ea-9304-61db668df30f.png)

**Comment by inire** [comment]
[logs.zip](https://github.com/ForgottenGlory/Living-Skyrim/files/4393972/logs.zip)

**Comment by ForgottenGlory** [comment]
Fixed for 1.5.0
