### ISSUE TITLE
Outdated Mods/Missing nexus links

### ISSUE THREAD

**Issue by jondood** [ForgottenGlory/Living-Skyrim#72]
Forgotten Dungeons
https://www.nexusmods.com/skyrimspecialedition/mods/449?tab=files
Has been updated, no longer any link to the required version.

Tittilating Barrels
https://www.nexusmods.com/skyrimspecialedition/mods/30497
Currently under review by nexus.

**Comment by ForgottenGlory** [comment]
Fixed 1.4.2
