### ISSUE TITLE
Skyrim SafeSave System Overhaul

### ISSUE THREAD

**Issue by Exoticusgaming** [ForgottenGlory/Living-Skyrim#73]
**Mod Name**
Skyrim SafeSave System Overhaul

**Mod Link**
[https://www.nexusmods.com/skyrimspecialedition/mods/19399](https://www.nexusmods.com/skyrimspecialedition/mods/19399
)

**Why?**
Will allow for configurable autosaves and will not save a inopportune times.

**Comment by ForgottenGlory** [comment]
From testing this seems to only work intermittently.
