### ISSUE TITLE
Problem with Hjoromir (v1.4.2)

### ISSUE THREAD

**Issue by Chris1013** [ForgottenGlory/Living-Skyrim#74]
There is a follower that you can pick up in Riverwood named Hjoromir.  After asking Hjoromir to follow me, and then deciding that I don't want him anymore, and dismissing him-he will say the dialogue that indicates he is leaving, but then continues to follow me.  There is nothing that I can do to dismiss him.  Similarly, when I try to trade him equipment, he will act like he is about to do so, but his equipment tab will never be shown.  I just can't get rid of this guy, and I can't adjust his equipment.

**Comment by ixanza** [comment]
This seems to be an issue with AFT.

@ForgottenGlory  can you take a look at the 3DNPC Patch for AFT? I've seen this reported before in the LS Support chat on the Wabbajack Discord

**Comment by Chris1013** [comment]
I don't know if this is helpful or not, but I originally asked him to join me in the Riverwood Inn.  At the time I already had FaendaI as a follower.  I then asked Gorr if he would also follow me and he declined because I had too many followers.  I then dismissed Hjoromir and left the inn.  I thought I dismissed Hjoromir because I was able to then add Gorr, and because Hjoromir's response indicated he was leaving, but then I noticed he continues to follow me around.

**Comment by cmtwc** [comment]
> 
> 
> This seems to be an issue with AFT.
> 
> @ForgottenGlory can you take a look at the 3DNPC Patch for AFT? I've seen this reported before in the LS Support chat on the Wabbajack Discord

I was the one who brought that up on discord, but the patch didn't help - I still had the same issue. Could try using Nether's Follower Framework instead, it has integrated support for Interesting NPC followers.

**Comment by ForgottenGlory** [comment]
Should be resolved by replacing AFT with NFF in 1.5.0.
