### ISSUE TITLE
ELE Being Overridden

### ISSUE THREAD

**Issue by IAreNemesis** [ForgottenGlory/Living-Skyrim#75]
FormID 00045A1D EditorID RiftenMistveilBarracks inside Cell Block 3 Sub-block 1 is one of the ELE edits. This is being overridden by Guards_Armor_Replacer.esp. Unsure if this is intentional.

Noticed it while patching my music mod.

**Comment by IAreNemesis** [comment]
Addendum; FormID 00016DF4 EditorID MarkarthGuardTower inside Cell Block 4 Sub-block 8 has the same mod override.

**Comment by ForgottenGlory** [comment]
Fixed for 1.5.0
