### ISSUE TITLE
EEK's Immersive Whiterun/Interiors

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim#76]
**LE/Oldrim mods will be automatically rejected, do not submit them.**

**Mod Name**
EEK's Immersive Whiterun and EEK's Immersive Interiors

**Mod Link**
https://www.nexusmods.com/skyrimspecialedition/mods/15820 https://www.nexusmods.com/skyrimspecialedition/mods/10463

**Why?**
I have used it plenty of times and it gives whiterun so much more "life" to say the least. It makes all of the stores actual stores where you can look around and just admire how amazing it looks.

**Additional context**
It's used in Total Skyrim Overhaul and I think it looks absolutely amazing and I think everyone else will.

**Comment by ForgottenGlory** [comment]
EEK's absolutely destroys FPS, unfortunately. I'm going to be using the JK's Whiterun interiors once the whole set is complete.
