### ISSUE TITLE
Combat Gameplay Overhaul CGO

### ISSUE THREAD

**Issue by sweeper240** [ForgottenGlory/Living-Skyrim#79]
**LE/Oldrim mods will be automatically rejected, do not submit them.**

**Mod Name**
Combat Gameplay Overhaul - CGO

**Mod Link**
https://www.nexusmods.com/skyrimspecialedition/mods/33767

**Why?**
CGO adds several features and fixes to combat and movement. It has responsive dodge rolls, procedural leaning, grip changing, mid-air combat, striking with staffs, dual-wielding two-handed weapons, 1st & 3rd person weapon animations, and more.

This mod provide a superior, more dynamic experience in Skyrim. The end result is felt throughout the entire game making play more satisfying and enjoyable 

**Additional context**
![NfbJseb](https://user-images.githubusercontent.com/62799488/77824245-4b2cf480-70cf-11ea-8562-673a2802a375.png)

**Comment by natenater** [comment]
Here is the link for the SSE version:

https://www.nexusmods.com/skyrimspecialedition/mods/33767

**Comment by ForgottenGlory** [comment]
This mod is explicitly incompatible with FNIS, so it cannot be added to LS.
