### ISSUE TITLE
CTD starting a sales conversation with Lucan in Riverwood after giving him the golden claw back.

### ISSUE THREAD

**Issue by pgdeaner** [ForgottenGlory/Living-Skyrim#80]
**Make sure you are using the latest version of LS before reporting a bug.**
1.4.3

**Describe the bug**
CTD

**To Reproduce**
Get the quest for the claw, get claw, go to Riverwood, Give to Lucan in his shop.  When he gets done prattling about how grateful he is, try to sell the rest of the shit you collected to him.
CTD occurs before the inventory displays.  Even occurs if you try to sell to him first.  Weird.

**Expected behavior**
No CTD

**Screenshots**

**Additional context**
Not a show stopper.  Lucan is a dick anyway.

**Comment by ForgottenGlory** [comment]
Initial testing between myself and Haazen indicate this may be fixed. Fix will be included in 1.5.0
