### ISSUE TITLE
Nether's Follower Framework

### ISSUE THREAD

**Issue by Spanana576** [ForgottenGlory/Living-Skyrim#84]
**Mod Name**
Nether's Follower Framework

**Mod Link**
https://www.nexusmods.com/skyrimspecialedition/mods/18076

**Why?**
Much more intuitive and easier to work with than AFT. Also allows you to designate certain followers as healers. The only content it lacks in comparison to AFT is the posing system. 

**Additional context**
MCM Menu and it allows you to designate bases for followers.

**Comment by ForgottenGlory** [comment]
Replaces AFT in 1.5.0
