### ISSUE TITLE
CBP a little more active than would be immersive

### ISSUE THREAD

**Issue by pgdeaner** [ForgottenGlory/Living-Skyrim#9]
**LE/Oldrim mods will be automatically rejected, do not submit them.**

**Mod Name**
Immersive CBP config

**Mod Link**
https://www.nexusmods.com/skyrimspecialedition/mods/16380

**Why?**
My toon's boobs bounce like jello.

**Additional context**
If you want I can take a video.  :)

**Comment by ForgottenGlory** [comment]
Added v1.4.0
