### ISSUE TITLE
Patch for Sustained Magic Mod and Ordinator

### ISSUE THREAD

**Issue by axfred** [ForgottenGlory/Living-Skyrim#90]
**Mod Name**
Sustained Magic - Patches - Ordinator

**Mod Link**
https://www.nexusmods.com/skyrimspecialedition/mods/26450

**Why?**
In LS 1.4.3. Sustained Magic personal dispel spell removes sustained spells as well as summoned skeletons from the Ordinator Conjuration tree that requires many bones and revisiting an altar to resummon.
Also the patch fixes compatibility of Ordinator perks and Sustained Magic magicka costs.  I do not know for a fact that this patch will fix the skeleton issue but someone reported the issue in the patch forums and it appeared to be resolved by this patch.  

**Additional context**

**Comment by axfred** [comment]
I just checked the patch page and an combined Apocalypse/Ordinator patch exists also updated on Mar 20th.

**Comment by axfred** [comment]
I was going to open a new issue, but this is related to Sustained Magic and Apocalypse.  When casting Soul Cloak using the Apocalypse spell Ocato's Recital, Sustained Magic Mod reserves the magicka for this spell.  All other spells that I tested with Ocato's did not do this including flesh spells and the Alarm spell.  The Mar 20 SM/ Apocalypse patch may fix this.

**Comment by axfred** [comment]
It seems that every problem I have with this modlist involves the Sustained Magic mod not working properly or as expected.  Building a mage has been a real chore because of SM mod reserving either too much or a undesired magicka decrease.  Sometimes the same spell is reserved twice, like Bound Sword.  The dispel spell doesn't work on all spells or when expected and breaks ordinator skeletons.  It would be great if the Sustained Magic mod could be made optional in future releases if these issues can't be fixed.  Until then I am going to stick to melee or use another modlist.

**Comment by aryell2linx** [comment]
Sustained Magic can be a bit buggy, I found the bug with spells not dispelling correctly... candlelight comes to mind. but it is a must for a mage build... to switch to that spell that is meant to run for longer periods of time every time, becomes tiresome after a while... and then its just time to pull out a sword and abandon magic build for the most part without this kind of functionality... what it needs is an mcm menu. Or I must've missed it somewhere in the LS modlist if it has one already

**Comment by axfred** [comment]
I think if you add the combined patch Sustained Magic Patch for Apocalypse and Ordinator it would alleviate some of the problems with reserved magicka and should fix the skeleton problem. I notice someone in yesterday's discord comments bring up some Ordinator issues withe Sustained Magic also.  Please at least fix the Ordinator Conjuration Skeleton problem by applying the SM Apoc/Ordinator patch from Mar 20th. Thanks for the reply, Ax.

**Comment by ForgottenGlory** [comment]
I literally made the Sustained Magic - Ordinator patch included in this mod.
