### ISSUE TITLE
Enhanced Skyrim Factions - The Companions Guild

### ISSUE THREAD

**Issue by natenater** [ForgottenGlory/Living-Skyrim#91]
**LE/Oldrim mods will be automatically rejected, do not submit them.**

**Mod Name**
Enhanced Skyrim Factions - The Companions Guild

**Mod Link**
https://www.nexusmods.com/skyrim/mods/22650

**Why?**
This expands the companions by adding additional content and features.

**Comment by ForgottenGlory** [comment]
LE/Oldrim mods will be automatically rejected, do not submit them.

**Comment by natenater** [comment]
whoops, I can't read apperantly.
