### ISSUE TITLE
Bugfix Compilation

### ISSUE THREAD

**Issue by inire** [ForgottenGlory/Living-Skyrim#93]
**LE/Oldrim mods will be automatically rejected, do not submit them.**

**Mod Name**
Bugfix Compilation

**Mod Link**
https://www.nexusmods.com/skyrimspecialedition/mods/33449?tab=description

**Why?**
From the description it includes a number of other bug fixes in one, with permissions from the authors.     
1st Person Candlelight Fix by Savaas
Believable Crime Report Radius by Burnout6010
Better Dynamic Snow - Patches by Soupdragon
Better Dynamic Snow Stairs Fix by IKE200
Dawnguard Don't Hunt Cured Vampires by WetCement
Don't Talk With Your Mouth Full by Whitefang37
Dragon Stalking Fix by sevencardz
Dwemer Gates Don't Reset by tarlazo
Fast Travel Speed Fix by michaelrw 
Hunters Not Bandits by raccoondance
Immersive Cave Entrances by duinnin
Move it Dammit - for Skyrim Special Edition by Apogee777
Multiple Floors Sandboxing﻿ by Dovahklon
NARC Remade - No Animals Report Crimes for Skyrim SE by Pharros
No BS AI Projectile Dodge (Magic and Arrows) by Reize
No More Standing Too Close SSE by azzendix
No NPC Greetings (Special Edition) - Reduced Range Greetings options available by Cipscis-Reize
No Stretching by langley
NPC's Run and Walk at Your Pace by popcornsoda55
Raven Rock - Fix Exit on Horseback by AndrealphusVIII
Rude Imperial Soldiers Escort Prisoner fix by elite403
WoodElf - MaleHair - Fix ﻿by Provisioncore

**Additional context**
Should save a number of mod slots.

**Comment by ForgottenGlory** [comment]
Will be included in 1.6.0 when it's ready.

**Comment by ForgottenGlory** [comment]
Added v1.6.0
