### ISSUE TITLE
Parallax Pelts

### ISSUE THREAD

**Issue by Exoticusgaming** [ForgottenGlory/Living-Skyrim#94]
**Mod Name**
Parallax Pelts

**Mod Link**
https://www.nexusmods.com/skyrimspecialedition/mods/33839

**Why?**
Adds parallax enabled pelts.

**Additional context**
Requires SSE Parallax Shader Fix (BETA)
https://www.nexusmods.com/skyrimspecialedition/mods/31963

**Comment by ForgottenGlory** [comment]
This seems like overkill for pelts. Peltapalooza is fine.
