### ISSUE TITLE
Skyrim Weapons Expansion

### ISSUE THREAD

**Issue by natenater** [ForgottenGlory/Living-Skyrim#95]
**LE/Oldrim mods will be automatically rejected, do not submit them.**

**Mod Name**
Skyrim Weapons Expansion

**Mod Link**
https://www.nexusmods.com/skyrimspecialedition/mods/32500

**Why?**
This adds a ton of cool looking weapons

**Additional context**
![32500-1581214465-745152905](https://user-images.githubusercontent.com/62452629/78089731-3e8df200-7396-11ea-8cef-020d2fcca960.png)

**Comment by ForgottenGlory** [comment]
Added v1.6.0
