### ISSUE TITLE
Favorite Things - Extended Favorites Menu for SkyUI

### ISSUE THREAD

**Issue by Exoticusgaming** [ForgottenGlory/Living-Skyrim#96]
**Mod Name**
Favorite Things - Extended Favorites Menu for SkyUI

**Mod Link**
https://www.nexusmods.com/skyrimspecialedition/mods/27177

**Why?**
Expands the favorites menu in SkyUI for better visibility of items with longer names and other features

**Comment by ForgottenGlory** [comment]
Added v1.6.0
